version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "9283:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - my-network

  # api-gateway:
  #   image: api-gateway-image
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == manager
  #     labels:
  #       - "traefik.http.services.api-gateway.loadbalancer.server.port=8080"
  #     restart_policy:
  #       condition: any
  #   networks:
  #     - my-network

  front:
    build:
      context: ./app/frontend
    container_name: app-front
    ports:
      - "9282:80"

  #Micro-services
  # hotels:
  #   image: hotels-image
  #   deploy:
  #     replicas: 2
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '512M'
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - my-network

  # users:
  #   image: users-image
  #   environment:
  #     - DB_HOST=db
  #     - DB_USER=root
  #     - DB_PASSWORD=secret
  #   deploy:
  #     replicas: 2
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '512M'
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - my-network

  # vols:
  #   image: vols-image
  #       deploy:
  #   deploy:
  #     replicas: 2
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '512M'
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - my-network

  # evenements:
  #   image: evenements-image
  #   deploy:
  #     replicas: 2
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '512M'
  #     restart_policy:
  #       condition: on-failure

  #   networks:
  #     - my-network

  # bar:
  #   image: bar-image
  #   deploy:
  #     replicas: 2
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '512M'
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - my-network

  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: overlay
    attachable: true
